In [1]:
import numpy as n

In [2]:
x = n.array([1, 2, 3])
y = n.array([4, 5, 6])

In [3]:
x+y

array([5, 7, 9])

In [4]:
x*y

array([ 4, 10, 18])

In [5]:
print(x*y)

[ 4 10 18]


In [6]:
n.ones([3])

array([1., 1., 1.])

In [7]:
n.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
n.ones([3,4,5])

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [9]:
n.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
n.diag([3,4])

array([[3, 0],
       [0, 4]])

In [11]:
n.diag([1,2,3,4,5,6,7,8,9,0])

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 6, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 7, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 8, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 9, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [12]:
n.zeros(3)

array([0., 0., 0.])

In [13]:
n.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
x = n.arange(start=0, stop=35, step=3)
x

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33])

In [15]:
x = n.arange(0, 35, 3)
x

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33])

In [16]:
x[2:5:0]

ValueError: slice step cannot be zero

In [17]:
n.random.random()

0.9277601852358667

In [18]:
n.random.random(4)

array([0.68545794, 0.54193877, 0.82259415, 0.58184567])

In [19]:
n.random.random([3,4])

array([[0.27443809, 0.87313891, 0.22903494, 0.74597062],
       [0.94493952, 0.40522477, 0.2848922 , 0.149743  ],
       [0.70090718, 0.69180599, 0.75040044, 0.73383919]])

In [20]:
n.random.random(1, 1000)

TypeError: random_sample() takes at most 1 positional argument (2 given)

In [21]:
n.random.randint(1, 1000)

639

In [22]:
n.random.randint(1, 1000, 5)

array([618, 319,  69, 724, 130])

In [23]:
n.random.randint(1, 1000, [2,3])

array([[114,  74, 362],
       [683, 591, 842]])

In [24]:
n.random.randint([2,3])

TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'

In [25]:
x = n.random.randint(0,10,[3,3])
x

array([[5, 4, 7],
       [9, 6, 3],
       [3, 5, 6]])

In [26]:
x.T

array([[5, 9, 3],
       [4, 6, 5],
       [7, 3, 6]])

In [27]:
s = n.random.randint(0, 180, 50)

In [28]:
s.sort()
s

array([  7,   8,   9,  13,  14,  18,  22,  27,  29,  29,  36,  37,  41,
        53,  54,  54,  61,  62,  66,  72,  73,  77,  79,  81,  90,  91,
        91, 100, 104, 108, 108, 111, 111, 118, 123, 129, 130, 131, 139,
       149, 152, 156, 158, 164, 168, 170, 172, 172, 174, 178])

In [29]:
n.sin(s*n.pi/180)

array([0.12186934, 0.1391731 , 0.15643447, 0.22495105, 0.2419219 ,
       0.30901699, 0.37460659, 0.4539905 , 0.48480962, 0.48480962,
       0.58778525, 0.60181502, 0.65605903, 0.79863551, 0.80901699,
       0.80901699, 0.87461971, 0.88294759, 0.91354546, 0.95105652,
       0.95630476, 0.97437006, 0.98162718, 0.98768834, 1.        ,
       0.9998477 , 0.9998477 , 0.98480775, 0.97029573, 0.95105652,
       0.95105652, 0.93358043, 0.93358043, 0.88294759, 0.83867057,
       0.77714596, 0.76604444, 0.75470958, 0.65605903, 0.51503807,
       0.46947156, 0.40673664, 0.37460659, 0.27563736, 0.20791169,
       0.17364818, 0.1391731 , 0.1391731 , 0.10452846, 0.0348995 ])